name: CI Build

on:
  pull_request:
    paths-ignore:
      - '*.commits'
      - '*.markdown'
      - '**/*.markdown'

env:
  LC_ALL: en_US.UTF-8

jobs:
  CheckSourceFormatting:
    name: Check source formatting
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        shell: bash
        run: |
          ./gradlew --no-daemon checkSourceFormatting
  LinuxJDK8:
    name: Linux JDK8
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        shell: bash
        run: |
          ./run-tests.sh
      - name: Upload tests zip
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: LinuxJDK8-tests.zip
          path: tests.zip
  LinuxJDK11:
    name: Linux JDK11
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        shell: bash
        run: |
          ./run-tests.sh
      - name: Upload tests zip
        uses: actions/upload-artifact@v1
        if: failure() || success()
        with:
          name: LinuxJDK11-tests.zip
          path: tests.zip
  MacOSJDK8:
    name: MacOS JDK8
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        shell: bash
        run: |
          ./run-tests.sh
      - name: Upload tests zip
        uses: actions/upload-artifact@v1
        if: failure() || success()
        with:
          name: MacOSJDK8-tests.zip
          path: tests.zip